name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . -f Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/laravelintermediateapp

    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/laravelintermediateapp
