name: Build Result image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3


      - name: Build the Docker image
        run: sudo docker build . -f Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/laravelintermediateapp

      - name: Docker Push
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/laravelintermediateapp

      - name: Docker delete
        run: sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/laravelintermediateapp
        
